name: Flutter
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment: 
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  transparent_image: ^1.0.0
  cached_network_image: ^0.8.0
  english_words: ^3.1.0
  http: ^0.12.0
  web_socket_channel: 1.0.12
  carousel_slider: ^1.3.0
  page_view_indicators: ^1.2.0
  dynamic_list_view: ^0.1.5
  liquid_pull_to_refresh: ^1.1.0
  shared_preferences: ^0.5.2+1
  image_picker: ^0.6.0+9
  sqflite: ^1.1.0
  flutter_sound: ^1.4.1
  intl: ^0.15.6
  location: ^2.3.5
  video_player: ^0.10.1+3
  flutter_socket_io: ^0.4.7 
  loader_search_bar: ^1.0.3+3
  sy_flutter_widgets: ^0.1.4
  webview_flutter: ^0.3.9+1
  flutter_webview_plugin: ^0.3.5
  event_bus: ^1.1.0
  keyboard_visibility: ^0.5.6
  flutter_swiper : ^1.1.6
  flutter_staggered_grid_view: "^0.2.7"
  share: ^0.6.1+1
  share_extend: "^1.0.9"
  barcode_scan: ^0.0.3 
  easy_localization: ^1.2.0+1


dev_dependencies: 
  flutter_test:   
    sdk: flutter
  

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets: 
  - res/icons/ic_play.png
  - res/icons/2.0x/ic_play.png
  - res/icons/3.0x/ic_play.png
  - res/icons/ic_stop.png
  - res/icons/2.0x/ic_stop.png
  - res/icons/3.0x/ic_stop.png
  - res/icons/ic_pause.png
  - res/icons/2.0x/ic_pause.png
  - res/icons/3.0x/ic_pause.png
  - res/icons/ic_mic.png
  - res/icons/2.0x/ic_mic.png
  - res/icons/3.0x/ic_mic.png
  - res/icons/ic_volume_down.png
  - res/icons/2.0x/ic_volume_down.png
  - res/icons/3.0x/ic_volume_down.png
  - res/icons/ic_volume_up.png
  - res/icons/2.0x/ic_volume_up.png
  - res/icons/3.0x/ic_volume_up.png

  # assets begin
  # resources/* 
    - resources/.DS_Store
    - resources/images/home/guanwangshangcheng.png
    - resources/images/home/.DS_Store
    - resources/images/home/jiadianpinpai.png
    - resources/images/home/xiaoxishi.png
    - resources/images/home/wodekong.png
    - resources/images/home/shouyekong.png
    - resources/images/home/xiaoxikong.png
    - resources/images/home/shouyeshi.png
    - resources/images/home/shouji.png
    - resources/images/home/pinpaituijian.png
    - resources/images/home/shuma.png
    - resources/images/home/wodechanpin.png
    - resources/images/home/diannao.png
    - resources/images/home/fangdajing.png
    - resources/images/home/jiadian.png
    - resources/images/home/gouwucheshi.png
    - resources/images/home/jiajupinpai.png
    - resources/images/home/zaixiankefu.png
    - resources/images/home/logo.png
    - resources/images/home/wodeshi.png
    - resources/images/home/shoujipinpai.png
    - resources/images/home/aidian.png
    - resources/images/home/jiaju.png
    - resources/images/home/jiantou.png
    - resources/images/home/diannaoppinpai.png
    - resources/images/home/shumapinpai.png
    - resources/images/home/fuwudating.png
    - resources/images/home/gouwuchekong.png
    - resources/images/form/.DS_Store
    - resources/images/form/sanjiaogou.png
    - resources/images/form/shangmenweixiu.png
    - resources/images/form/gantanhao.png
    - resources/images/form/zuojiantou.png
    - resources/images/.DS_Store
    - resources/images/2.0x/sanjiaogou.png
    - resources/images/2.0x/shangmenweixiu.png
    - resources/images/2.0x/gantanhao.png
    - resources/images/2.0x/zuojiantou.png
    - resources/images/3.0x/sanjiaogou.png
    - resources/images/3.0x/shangmenweixiu.png
    - resources/images/3.0x/zuojiantou.png
    - resources/images/msgs/fuwutongzhi.png
    - resources/images/msgs/zhaohutongzhi.png
    - resources/images/msgs/huodongxiaoxi.png
    - resources/images/flower.jpg
    - resources/images/cart/gouxuankuang.png
    - resources/images/cart/lansegouxuan.png
    - resources/images/lake.jpg
    - resources/images/mall/fapiaoyoujiantou.png
    - resources/images/mall/.DS_Store
    - resources/images/mall/genduo.png
    - resources/images/mall/fanhui.png
    - resources/images/mall/zaixiankefu.png
    - resources/images/mall/fuwushangcheng.png
    - resources/images/mall/shangla.png
    - resources/images/mall/fuwudating.png
    - resources/images/mall/fenxiang.png
    - resources/langs/zh-CN.json
    - resources/langs/en-US.json
  # assets end

  
 
  


   
 

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
